kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terraform-k8s
subjects:
- kind: ServiceAccount
  name: terraform-k8s
roleRef:
  kind: Role
  name: terraform-k8s
  apiGroup: rbac.authorization.k8s.io
