name: Go Build & Test
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.8
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1.3.1
      with:
        args: release --snapshot --skip-publish --rm-dist --skip-sign